[mypy]
ignore_missing_imports = True
check_untyped_defs = True

[mypy-pysat.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-pycmsgen.*]
ignore_missing_imports = True
