[build-system]
requires = ["setuptools>=80.10.2", "Cython>=3.2.4"]
build-backend = "setuptools.build_meta"

[project]
name = "314"
version = "0.1.0"
description = "An extensible data-driven QBF/DQBF solver"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cython>=3.2.4",
    "numpy>=2.4.2",
    "pycmsgen>=6.1.1",
    "python-sat>=1.8.dev30",
    "scikit-learn>=1.8.0",
    "setuptools>=80.10.2",
]

[dependency-groups]
dev = ["pytest>=9.0.2", "ruff", "mypy"]

[tool.pytest.ini_options]
pythonpath = "src"